# Generated by Django 4.2 on 2026-03-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_no',
            new_name='room_number',
        ),
    ]
