# Generated by Django 4.2 on 2026-03-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rename_room_no_room_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenence', 'Maintenance')], default='available', max_length=20),
        ),
    ]
