# Generated by Django 4.2 on 2026-03-17 21:53
from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_default_admin(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    User = apps.get_model("accounts", "User")

    role, _ = Role.objects.get_or_create(role_name="Admin")

    user, created = User.objects.get_or_create(
        username="admin",
        defaults={
            "role": role,
            "is_staff": True,
            "is_superuser": True,
            "is_active": True,
            "email": "admin@gmail.com",
            "password": make_password("admin123"),
        },
    )

    if not created:
        user.role = role
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.email = "admin@gmail.com"
        user.password = make_password("admin123")
        user.save()


def remove_default_admin(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(username="admin").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.RunPython(create_default_admin, remove_default_admin),
    ]

# from django.db import migrations
# from django.contrib.auth.hashers import make_password


# class Migration(migrations.Migration):

#     dependencies = [
#         ('accounts', '0002_alter_user_role'),
#     ]

#     operations = [
#     ]
